class CfgDifficulties
{
	default = "Veteran";
	defaultNormal = "Veteran";
	defaultEasy = "Veteran";
	defaultHard = "Veteran";
	class Recruit
	{
		displayName = "$STR_Difficulty2";
		description = "$STR_Difficulty2_desc";
		showCadetHints = 0;
		showCadetWP = 1;
		maxPilotHeight = 10000;
		scoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		scoreChar = "*";
		badScoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		badScoreChar = "X";
		levelAI = "AILevelHigh";
		myArmorCoef = 1.2;
		groupArmorCoef = 1.1;
		peripheralVisionAid = 0.6;
		visionAid = 0;
		HealSpeedMedicMedikit = 0.1;
		HealSpeedMedicFAK = 0.1;
		HealSpeedMedic = 0.1;
		HealSpeedSoldierFAK = 0.04;
		HealSpeedSoldier = 0.04;
		BleedingRate = 0.08;
		CancelThreshold = 0.2;
		DivingLimitMultiplier = 1.0;
		recoilCoef = 1;
		autoReload = 0;
		animSpeedCoef = 0;
		class Flags
		{
			armor[] = {0,0};
			friendlyTag[] = {0,0};
			enemyTag[] = {0,0};
			mineTag[] = {0,0};
			hud[] = {0,0};
			hudPerm[] = {0,0};
			hudWp[] = {0,0};
			hudWpPerm[] = {0,0};
			stanceIndicator[] = {1,0};
			autoSpot[] = {0,0};
			map[] = {0,0};
			weaponCursor[] = {0,0};
			autoGuideAT[] = {0,0};
			clockIndicator[] = {0,0};
			3rdPersonView[] = {0,0};
			unlimitedSaves[] = {0,0};
			deathMessages[] = {0,0};
			netStats[] = {0,0};
			vonId[] = {0,0};
			cameraShake[] = {1,1};
			hudGroupInfo[] = {0,0};
			extendetInfoType[] = {0,0};
		};
	};
	class Regular
	{
		displayName = "$STR_Difficulty2";
		description = "$STR_Difficulty2_desc";
		showCadetHints = 0;
		showCadetWP = 1;
		maxPilotHeight = 10000;
		scoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		scoreChar = "*";
		badScoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		badScoreChar = "X";
		levelAI = "AILevelHigh";
		myArmorCoef = 1.2;
		groupArmorCoef = 1.1;
		peripheralVisionAid = 0.6;
		visionAid = 0;
		HealSpeedMedicMedikit = 0.1;
		HealSpeedMedicFAK = 0.1;
		HealSpeedMedic = 0.1;
		HealSpeedSoldierFAK = 0.04;
		HealSpeedSoldier = 0.04;
		BleedingRate = 0.08;
		CancelThreshold = 0.2;
		DivingLimitMultiplier = 1.0;
		recoilCoef = 1;
		autoReload = 0;
		animSpeedCoef = 0;
		class Flags
		{
			armor[] = {0,0};
			friendlyTag[] = {0,0};
			enemyTag[] = {0,0};
			mineTag[] = {0,0};
			hud[] = {0,0};
			hudPerm[] = {0,0};
			hudWp[] = {0,0};
			hudWpPerm[] = {0,0};
			stanceIndicator[] = {1,0};
			autoSpot[] = {0,0};
			map[] = {0,0};
			weaponCursor[] = {0,0};
			autoGuideAT[] = {0,0};
			clockIndicator[] = {0,0};
			3rdPersonView[] = {0,0};
			unlimitedSaves[] = {0,0};
			deathMessages[] = {0,0};
			netStats[] = {0,0};
			vonId[] = {0,0};
			cameraShake[] = {1,1};
			hudGroupInfo[] = {0,0};
			extendetInfoType[] = {0,0};
		};
	};
	class Veteran
	{
		displayName = "$STR_Difficulty2";
		description = "$STR_Difficulty2_desc";
		showCadetHints = 0;
		showCadetWP = 1;
		maxPilotHeight = 10000;
		scoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		scoreChar = "*";
		badScoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		badScoreChar = "X";
		levelAI = "AILevelHigh";
		myArmorCoef = 1.2;
		groupArmorCoef = 1.1;
		peripheralVisionAid = 0.6;
		visionAid = 0;
		HealSpeedMedicMedikit = 0.1;
		HealSpeedMedicFAK = 0.1;
		HealSpeedMedic = 0.1;
		HealSpeedSoldierFAK = 0.04;
		HealSpeedSoldier = 0.04;
		BleedingRate = 0.08;
		CancelThreshold = 0.2;
		DivingLimitMultiplier = 1.0;
		recoilCoef = 1;
		autoReload = 0;
		animSpeedCoef = 0;
		class Flags
		{
			armor[] = {0,0};
			friendlyTag[] = {0,0};
			enemyTag[] = {0,0};
			mineTag[] = {0,0};
			hud[] = {0,0};
			hudPerm[] = {0,0};
			hudWp[] = {0,0};
			hudWpPerm[] = {0,0};
			stanceIndicator[] = {1,0};
			autoSpot[] = {0,0};
			map[] = {0,0};
			weaponCursor[] = {0,0};
			autoGuideAT[] = {0,0};
			clockIndicator[] = {0,0};
			3rdPersonView[] = {0,0};
			unlimitedSaves[] = {0,0};
			deathMessages[] = {0,0};
			netStats[] = {0,0};
			vonId[] = {0,0};
			cameraShake[] = {1,1};
			hudGroupInfo[] = {0,0};
			extendetInfoType[] = {0,0};
		};
	};
	class Mercenary
	{
		displayName = "$STR_Difficulty2";
		description = "$STR_Difficulty2_desc";
		showCadetHints = 0;
		showCadetWP = 1;
		maxPilotHeight = 10000;
		scoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		scoreChar = "*";
		badScoreImage = "#(argb,8,8,3)color(1,1,1,1)";
		badScoreChar = "X";
		levelAI = "AILevelHigh";
		myArmorCoef = 1.2;
		groupArmorCoef = 1.1;
		peripheralVisionAid = 0.6;
		visionAid = 0;
		HealSpeedMedicMedikit = 0.1;
		HealSpeedMedicFAK = 0.1;
		HealSpeedMedic = 0.1;
		HealSpeedSoldierFAK = 0.04;
		HealSpeedSoldier = 0.04;
		BleedingRate = 0.08;
		CancelThreshold = 0.2;
		DivingLimitMultiplier = 1.0;
		recoilCoef = 1;
		autoReload = 0;
		animSpeedCoef = 0;
		class Flags
		{
			armor[] = {0,0};
			friendlyTag[] = {0,0};
			enemyTag[] = {0,0};
			mineTag[] = {0,0};
			hud[] = {0,0};
			hudPerm[] = {0,0};
			hudWp[] = {0,0};
			hudWpPerm[] = {0,0};
			stanceIndicator[] = {1,0};
			autoSpot[] = {0,0};
			map[] = {0,0};
			weaponCursor[] = {0,0};
			autoGuideAT[] = {0,0};
			clockIndicator[] = {0,0};
			3rdPersonView[] = {0,0};
			unlimitedSaves[] = {0,0};
			deathMessages[] = {0,0};
			netStats[] = {0,0};
			vonId[] = {0,0};
			cameraShake[] = {1,1};
			hudGroupInfo[] = {0,0};
			extendetInfoType[] = {0,0};
		};
	};
};